{% set name = "omexml-dls" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../


build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:

  host:
    - python >=2.7
    - pip
  run:
    - python >=2.7
    - future

test:
  imports:
    - oxdls

about:
  home: https://github.com/DiamondLightSource/python-{{ name }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Package to help simply and consistently create and parse OME metadata for B24 of Diamond Light Source Ltd.'

  description: |
    This is a modified copy of python_bioformats' omexml.py with a section 
    from the Allen Institute for Cell Science's aicsimageio version of 
    omexml.py (indicated within the file). This package extends 
    capabilities, predominantly in terms of ROIs, while offering a 
    light-weight distribution of the omexml file.
  doc_url: https://github.com/DiamondLightSource/python-{{ name }}/blob/master/README.md
  dev_url: https://github.com/DiamondLightSource/python-{{ name }}

extra:
  recipe-maintainers:
    - thomasmfish